### ISSUE TITLE
improve user id issues

### ISSUE THREAD

**Issue by jleni** [Zondax/docker-builder#3]
One possibility is to root and chmod 666 everything that is mounted or shared

**Comment by Demi-Marie** [comment]
With Podman, we won’t need root privileges.

**Comment by jleni** [comment]
Yes, I would love to completely move to podman, however, there are people that want to build in OSX..

**Comment by Demi-Marie** [comment]
We can use podman if it is available, and fall back to docker otherwise.

**Comment by jleni** [comment]
We added all three normal users to bolos 1000, 1001, 501. That covers the typical development environment and does not force people to install podman
