### ISSUE TITLE
Check signatures of release tarballs | Bolos container

### ISSUE THREAD

**Issue by Demi-Marie** [Zondax/docker-builder#4]
We need to check the signatures of the release tarballs to ensure they have not been tampered with.  Checking the SHA2 hash is an acceptable alternative, provided the hash is hard-coded in the build script.

**Comment by jleni** [comment]
Done as part of this PR 
https://github.com/Zondax/docker-builder/commit/404f3e51e4b3b84a7d4886965afc171ab80326dd
