### ISSUE TITLE
Publish containers using github commit hash

### ISSUE THREAD

**Issue by jleni** [Zondax/docker-builder#7]

**Comment by emmanuelm41** [comment]
Work progress: 
- [ ] zondax/builder-base
- [ ] zondax/builder-yocto
- [x] zondax/builder-bolos 
- [ ] zondax/builder-zemu
- [x] zondax/circleci
- [ ] zondax/rust-ci

**Comment by jleni** [comment]
Mm.. can we split this in multiple issues?

**Comment by emmanuelm41** [comment]
Splitted. I will close this issue as I created one to each image.
